# Week 1: Linear Regression 1

In [22]:
import pandas as pd
import numpy as np

In [2]:
df1_animation = pd.read_csv("data/Animation_Movies.csv")
df2_action = pd.read_csv("data/action.csv")
df3_nvda = pd.read_csv("data/NVDA.csv")

### Dataframe 1:

In [3]:
df1_animation.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_language,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages
0,150540,Inside Out,7.922,19463,Released,2015-06-09,857611174,95,False,/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg,...,en,Inside Out,"Growing up can be a bumpy road, and it's no ex...",107.292,/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg,Meet the little voices inside your head.,"Animation, Family, Adventure, Drama, Comedy","Pixar, Walt Disney Pictures",United States of America,English
1,14160,Up,7.949,18857,Released,2009-05-28,735099082,96,False,/hGGC9gKo7CFE3fW07RA587e5kol.jpg,...,en,Up,Carl Fredricksen spent his entire life dreamin...,90.968,/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg,The greatest adventure is just getting back home.,"Animation, Comedy, Family, Adventure",Pixar,United States of America,English
2,12,Finding Nemo,7.824,18061,Released,2003-05-30,940335536,100,False,/h3uqFk7sZRJvLZDdLiFB9qwbL07.jpg,...,en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",55.456,/ggQ6o8X5984OCh3kZi2UIJQJY5y.jpg,There are 3.7 trillion fish in the ocean. They...,"Animation, Family",Pixar,United States of America,English
3,354912,Coco,8.222,17742,Released,2017-10-27,800526015,105,False,/askg3SMvhqEl4OL52YuvdtY40Yb.jpg,...,en,Coco,Despite his family’s baffling generations-old ...,166.578,/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg,The celebration of a lifetime,"Family, Animation, Fantasy, Music, Comedy, Adv...","Pixar, Walt Disney Pictures",United States of America,"English, Spanish"
4,10681,WALL·E,8.078,17446,Released,2008-06-22,521311860,98,False,/fK5ssgvtI43z19FoWigdlqgpLRE.jpg,...,en,WALL·E,What if mankind had to leave Earth and somebod...,58.517,/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg,After 700 years of doing what he was built for...,"Animation, Family, Science Fiction","Pixar, Walt Disney Pictures",United States of America,English

In [4]:
df1_animation.info()

<class 'pandas.DataFrame'>
RangeIndex: 51945 entries, 0 to 51944
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    51945 non-null  int64
 1   title                 51944 non-null  str
 2   vote_average          51945 non-null  float64
 3   vote_count            51945 non-null  int64
 4   status                51945 non-null  str
 5   release_date          49808 non-null  str
 6   revenue               51945 non-null  int64
 7   runtime               51945 non-null  int64
 8   adult                 51945 non-null  bool
 9   backdrop_path         15835 non-null  str
 10  budget                51945 non-null  int64
 11  homepage              8253 non-null   str
 12  imdb_id               29552 non-null  str
 13  original_language     51945 non-null  str
 14  original_title        51944 non-null  str
 15  overview              45866 non-null  str
 16  popularity            51945 non-null  float64
 17  poster_path           37934 non-null  str
 18  tagline               4678 non-null   str
 19  genres                51945 non-null  str
 20  production_companies  29398 non-null  str
 21  production_countries  39700 non-null  str
 22  spoken_languages      33818 non-null  str
dtypes: bool(1), float64(2), int64(5), str(15)
memory usage: 8.8 MB

#### Cleaning Dataframe 1

In [5]:
df1_animation.isnull().sum()

id                          0
title                       1
vote_average                0
vote_count                  0
status                      0
release_date             2137
revenue                     0
runtime                     0
adult                       0
backdrop_path           36110
budget                      0
homepage                43692
imdb_id                 22393
original_language           0
original_title              1
overview                 6079
popularity                  0
poster_path             14011
tagline                 47267
genres                      0
production_companies    22547
production_countries    12245
spoken_languages        18127
dtype: int64

In [6]:
df1_animation.duplicated().sum()

np.int64(0)

In [7]:
df1_animation[df1_animation.duplicated()]

Empty DataFrame
Columns: [id, title, vote_average, vote_count, status, release_date, revenue, runtime, adult, backdrop_path, budget, homepage, imdb_id, original_language, original_title, overview, popularity, poster_path, tagline, genres, production_companies, production_countries, spoken_languages]
Index: []

[0 rows x 23 columns]

In [8]:
missing_percent = df1_animation.isnull().mean() * 100

missing_percent.sort_values(ascending=False)

tagline                 90.994321
homepage                84.112042
backdrop_path           69.515834
production_companies    43.405525
imdb_id                 43.109058
spoken_languages        34.896525
poster_path             26.972760
production_countries    23.573010
overview                11.702763
release_date             4.113967
original_title           0.001925
title                    0.001925
id                       0.000000
vote_count               0.000000
vote_average             0.000000
revenue                  0.000000
status                   0.000000
adult                    0.000000
budget                   0.000000
original_language        0.000000
runtime                  0.000000
popularity               0.000000
genres                   0.000000
dtype: float64

In [9]:
columns_to_drop = [
    "tagline",
    "homepage",
    "backdrop_path",
    "poster_path"
]

df1_animation = df1_animation.drop(columns=columns_to_drop)

In [15]:
df1_animation.shape

(51945, 19)

In [16]:
df1_animation["id"].duplicated().sum()

np.int64(0)

In [17]:
df1_animation["release_date"] = pd.to_datetime(
    df1_animation["release_date"],
    errors="coerce"
)

In [18]:
df1_animation["release_date"].head()

0   2015-06-09
1   2009-05-28
2   2003-05-30
3   2017-10-27
4   2008-06-22
Name: release_date, dtype: datetime64[us]

In [19]:
df1_animation["release_date"].isnull().sum()

np.int64(2137)

In [20]:
df1_animation[[
    "vote_average",
    "vote_count",
    "revenue",
    "runtime",
    "budget",
    "popularity"
]].describe()

,vote_average,vote_count,revenue,runtime,budget,popularity
count,51945.000000,51945.000000,5.194500e+04,51945.000000,5.194500e+04,51945.000000
mean,2.597083,40.395380,1.863464e+06,20.901415,5.759513e+05,1.886233
std,3.318748,482.705948,3.049824e+07,39.016002,7.606628e+06,9.700913
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,0.000000,0.000000,0.000000e+00,3.000000,0.000000e+00,0.600000
50%,0.000000,0.000000,0.000000e+00,7.000000,0.000000e+00,0.600000
75%,6.000000,2.000000,0.000000e+00,19.000000,0.000000e+00,0.882000
max,10.000000,19463.000000,1.450027e+09,3720.000000,2.600000e+08,1008.942000

In [21]:
columns = [
    "vote_average",
    "vote_count",
    "revenue",
    "runtime",
    "budget",
    "popularity"
]

(df1_animation[columns] == 0).sum()

vote_average    30789
vote_count      30779
revenue         50845
runtime          6301
budget          50342
popularity        963
dtype: int64

In [24]:
df1_animation["budget"] = df1_animation["budget"].replace(0, np.nan)
df1_animation["revenue"] = df1_animation["revenue"].replace(0, np.nan)
df1_animation["runtime"] = df1_animation["runtime"].replace(0, np.nan)

df1_animation[["budget", "revenue", "runtime"]].isnull().sum()

budget     50342
revenue    50845
runtime     6301
dtype: int64

In [25]:
df1_animation[
    (df1_animation["vote_average"] == 0) &
    (df1_animation["vote_count"] > 0)
][["title", "vote_average", "vote_count"]]

                                           title  vote_average  vote_count
13117                               Dissolutions           0.0           2
13295                               Little Thing           0.0           2
14834                                        Fly           0.0           1
14968         Rising Waters In Underwood Springs           0.0           1
15050                         A Wiz named WuKong           0.0           1
15474                                      Augur           0.0           1
15499    Highlights Watch & Learn!: Holiday Fun!           0.0           1
15590                           Tomorrow My Love           0.0           1
15691                           Summer with Kuro           0.0           1
15864                                    Siva II           0.0           1
16490     Day Break Illusion: Fumikomenai Kokoro           0.0           1
16658                       Gode Save the Gouine           0.0           1
16914                              The Courtyard           0.0           1
17179                 Dick Pics! (A Documentary)           0.0           1
17449                              Antique Heart           0.0           1
17590                             Wind's Embrace           0.0           1
17788                  Dix-huit kilomètres trois           0.0           1
17854          In the Jungle There Is Much to Do           0.0           1
18032                        Five Improvisations           0.0           1
18163                       The Perfect Equation           0.0           1
18355                        King of Sea - Kwoon           0.0           1
18371                         Bakugan Evolutions           0.0           1
18535                        The Little Princess           0.0           1
18650                             Kanon Kazahana           0.0           1
18736                Mickey, L'Aventure Spatiale           0.0           1
18742                        Daughter of the Sun           0.0           1
18750                                      G'day           0.0           1
18824                                 Good Humor           0.0           1
19389                                Hell's Fire           0.0           1
19474                 This Is Not Frank's Planet           0.0           1
19557     Mike The Knight: Mikes Bravest Mission           0.0           1
20006  VeggieTales: Lessons from the Sock Drawer           0.0           1

In [26]:
df1_animation[
    (df1_animation["vote_count"] == 0) &
    (df1_animation["vote_average"] != 0)
][["title", "vote_average", "vote_count"]]

                                     title  vote_average  vote_count
21554                    Looking For Santa           6.0           0
24205                            Passenger           7.0           0
27253                               Hecate           3.0           0
28392                                Yampa          10.0           0
31599                         Being Pretty           5.0           0
32101                  Three Jolly Fellows           9.0           0
37475            The Goofy Adventure Story           6.0           0
38466                             After Us           6.0           0
38560                          Lost Senses           7.0           0
38944                Recently in the Woods           3.0           0
39682                       Uncle Elephant           5.0           0
40319                   Shooting Star Lens           4.0           0
40737                     The Caliph Stork           5.0           0
41507                    The Mighty Hunter           5.0           0
42344              Chips Off the Old Block          10.0           0
42705             Animation School Dropout           6.0           0
42733                          Brain Lapse           7.0           0
43330                      Joys And Glooms           5.0           0
44788        Tom Goes to the Mayor Returns           5.0           0
47780                      Trona Pinnacles           5.0           0
48812  Kingdom Under the Sea: The Red Tide           6.0           0
49903       Velké dobrodružství Čtyřlístku           5.0           0

### Dataframe 2:

In [10]:
df2_action.head()

,movie_id,movie_name,year,certificate,runtime,genre,rating,description,director,director_id,star,star_id,votes,gross(in $)
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,The people of Wakanda fight to protect their h...,Ryan Coogler,/name/nm3363032/,"Letitia Wright, \nLupita Nyong'o, \nDanai Guri...","/name/nm4004793/,/name/nm2143282/,/name/nm1775...",204835.0,NaN
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,Jake Sully lives with his newfound family form...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",295119.0,NaN
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,A pilot finds himself caught in a war zone aft...,Jean-François Richet,/name/nm0724938/,"Gerard Butler, \nMike Colter, \nTony Goldwyn, ...","/name/nm0124930/,/name/nm1591496/,/name/nm0001...",26220.0,NaN
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,A middle-aged Chinese immigrant is swept up in...,"Dan Kwan, \nDaniel Scheinert",/name/nm3453283/,"Michelle Yeoh, \nStephanie Hsu, \nJamie Lee Cu...","/name/nm3215397/,/name/nm0000706/,/name/nm3513...",327858.0,NaN
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Dom Toretto and his family are targeted by the...,Louis Leterrier,/name/nm0504642/,"Vin Diesel, \nJordana Brewster, \nTyrese Gibso...","/name/nm0004874/,/name/nm0108287/,/name/nm0879...",NaN,NaN

In [11]:
df2_action.info()

<class 'pandas.DataFrame'>
RangeIndex: 52452 entries, 0 to 52451
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     52452 non-null  str
 1   movie_name   52451 non-null  str
 2   year         44193 non-null  str
 3   certificate  13668 non-null  str
 4   runtime      32530 non-null  str
 5   genre        52452 non-null  str
 6   rating       29448 non-null  float64
 7   description  52452 non-null  str
 8   director     47819 non-null  str
 9   director_id  47819 non-null  str
 10  star         43212 non-null  str
 11  star_id      44621 non-null  str
 12  votes        29450 non-null  float64
 13  gross(in $)  2760 non-null   float64
dtypes: float64(3), str(11)
memory usage: 5.6 MB

### Dataframe 3:

In [12]:
df3_nvda.head()

         Date      Open      High       Low     Close  Adj Close    Volume
0  2000-01-03  0.984375  0.992188  0.919271  0.975260   0.894608  30091200
1  2000-01-04  0.958333  0.960938  0.901042  0.949219   0.870721  30048000
2  2000-01-05  0.921875  0.937500  0.904948  0.917969   0.842055  18835200
3  2000-01-06  0.917969  0.917969  0.822917  0.858073   0.787112  12048000
4  2000-01-07  0.854167  0.881510  0.841146  0.872396   0.800251   7118400

In [13]:
df3_nvda.info()

<class 'pandas.DataFrame'>
RangeIndex: 6116 entries, 0 to 6115
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6116 non-null   str
 1   Open       6116 non-null   float64
 2   High       6116 non-null   float64
 3   Low        6116 non-null   float64
 4   Close      6116 non-null   float64
 5   Adj Close  6116 non-null   float64
 6   Volume     6116 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 334.6 KB