## Week 4

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [2]:
df1_animation = pd.read_csv("data/Animation_Movies_clean.csv")

In [4]:
df1_animation["budget"] = df1_animation["budget"].replace(0, np.nan)
df1_animation["revenue"] = df1_animation["revenue"].replace(0, np.nan)
df1_animation["popularity"] = df1_animation["popularity"].replace(0, np.nan)
df1_animation["runtime"] = df1_animation["runtime"].replace(0, np.nan)

In [5]:
df1_animation["log_budget"] = np.log10(
    df1_animation["budget"]
)

df1_animation["log_popularity"] = np.log10(
    df1_animation["popularity"]
)

df1_animation["log_revenue"] = np.log10(
    df1_animation["revenue"]
)

In [6]:
animation_week4 = df1_animation.dropna(
    subset=[
        "log_budget",
        "log_popularity",
        "vote_average",
        "vote_count",
        "runtime",
        "log_revenue"
    ]
).copy()

animation_week4.shape

(616, 23)

In [7]:
median_revenue = animation_week4["log_revenue"].median()

median_revenue

np.float64(7.463266498273276)

In [8]:
animation_week4["high_revenue"] = (
    animation_week4["log_revenue"] > median_revenue
).astype(int)

In [9]:
animation_week4["high_revenue"].value_counts()

high_revenue
1    308
0    308
Name: count, dtype: int64

In [10]:
animation_week4["high_revenue"].value_counts(normalize=True)

high_revenue
1    0.5
0    0.5
Name: proportion, dtype: float64

In [12]:
features = [
    "log_budget",
    "log_popularity",
    "vote_average",
    "vote_count",
    "runtime"
]

X = animation_week4[features]
y = animation_week4["high_revenue"]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [15]:
log_model = LogisticRegression()

log_model.fit(
    X_train_scaled,
    y_train
)

y_pred = log_model.predict(X_test_scaled)

In [16]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.8951612903225806

In [17]:
cm = confusion_matrix(
    y_test,
    y_pred
)

cm

array([[54,  8],
       [ 5, 57]])

In [18]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.92      0.87      0.89        62
           1       0.88      0.92      0.90        62

    accuracy                           0.90       124
   macro avg       0.90      0.90      0.90       124
weighted avg       0.90      0.90      0.90       124

In [19]:
coefficients = pd.DataFrame({
    "Feature": features,
    "Coefficient": log_model.coef_[0]
})

coefficients.sort_values(
    "Coefficient",
    ascending=False
)

          Feature  Coefficient
0      log_budget     3.012154
3      vote_count     1.757297
1  log_popularity     1.702719
4         runtime    -0.105955
2    vote_average    -0.715851

### Dataframe 2

In [20]:
df2_action = pd.read_csv("data/Action_Movies_clean.csv")

In [21]:
df2_action["log_votes"] = np.log10(
    df2_action["votes"]
)

df2_action["log_gross"] = np.log10(
    df2_action["gross(in $)"]
)

In [22]:
action_week4 = df2_action.dropna(
    subset=[
        "log_votes",
        "rating",
        "runtime",
        "year",
        "log_gross"
    ]
).copy()

action_week4.shape

(2758, 16)

In [23]:
gross_median = action_week4["log_gross"].median()

action_week4["high_gross"] = (
    action_week4["log_gross"] > gross_median
).astype(int)

In [24]:
action_week4["high_gross"].value_counts()

high_gross
1    1379
0    1379
Name: count, dtype: int64

In [25]:
action_week4["high_gross"].value_counts(normalize=True)

high_gross
1    0.5
0    0.5
Name: proportion, dtype: float64

In [26]:
features = [
    "log_votes",
    "rating",
    "runtime",
    "year"
]

X = action_week4[features]
y = action_week4["high_gross"]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [28]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [29]:
log_model_action = LogisticRegression(
    max_iter=1000
)

log_model_action.fit(
    X_train_scaled,
    y_train
)

y_pred = log_model_action.predict(
    X_test_scaled
)

In [30]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.8478260869565217

In [31]:
cm = confusion_matrix(
    y_test,
    y_pred
)

cm

array([[226,  50],
       [ 34, 242]])

In [32]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.87      0.82      0.84       276
           1       0.83      0.88      0.85       276

    accuracy                           0.85       552
   macro avg       0.85      0.85      0.85       552
weighted avg       0.85      0.85      0.85       552

In [33]:
coefficients_action = pd.DataFrame({
    "Feature": features,
    "Coefficient": log_model_action.coef_[0]
})

coefficients_action.sort_values(
    "Coefficient",
    ascending=False
)

     Feature  Coefficient
0  log_votes     3.483641
2    runtime    -0.110902
1     rating    -0.611550
3       year    -0.691733